apiVersion: v2
name: argo-events
description: A Helm chart for Kubernetes
type: application
version: 2.4.0
appVersion: "v1.8.0"
dependencies:
  - name: argo-events
    version: 2.4.0
    repository: https://argoproj.github.io/argo-helm
